### PR TITLE
Set pipefail on the shell.

### PR DESCRIPTION
**Pull request by bfabio**
Set pipefail in order to have the piped RUNs fail even if the
last command exits successfully.

### CODE REVIEW

**Comment by amusarra** [comment]
@bfabio  Thank you for your contribution. I have to understand why the build task on Travis CI fails.

**Comment by bfabio** [comment]
@amusarra You're welcome. Looks like `DOCKER_USERNAME` (and possibly `DOCKER_PASSWORD`) is not set in Travis' environment for master.

**Comment by amusarra** [comment]
it's strange because I've never had problems with the travis build, just look at the history of previous builds.  I'll try to understand.

**Comment by bfabio** [comment]
@amusarra Oh yeah, that's because those variables are unavailable to PRs because a malicious one could exfiltrate them.

We need them just to push to Docker Hub, so I'd say we should login only before `make release`.

FYI, Docker Hub does automated builds out of the box and can potentially replace most of the script.

**Comment by amusarra** [comment]
Hi @bfabio 
I solved it by editing the travis configuration file. I know I could build directly from Docker Hub, but I prefer to use my good Makefile and do it from Travis CI. Thank you.

**Pull request merged**
